FROM mcr.microsoft.com/dotnet/runtime:6.0 as base
WORKDIR /app
EXPOSE 8086

FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /src

COPY ["Vehicle/Vehicle.csproj", "Vehicle/"]
COPY ["TrafficCoordinationSystem/TrafficCoordinationSystem.csproj", "TrafficCoordinationSystem/"]
RUN dotnet restore TrafficCoordinationSystem/TrafficCoordinationSystem.csproj
COPY . .

WORKDIR /src/TrafficCoordinationSystem
RUN dotnet build TrafficCoordinationSystem.csproj -c Release -o /app

FROM build as publish
RUN dotnet publish TrafficCoordinationSystem.csproj -c Release -o /app

FROM base as final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT [ "dotnet" , "TrafficCoordinationSystem.dll"]