FROM mcr.microsoft.com/dotnet/runtime:6.0 as base
WORKDIR /app
EXPOSE 8085

FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /src

COPY ["Vehicle/Vehicle.csproj", "Vehicle/"]
COPY ["VehicleFaking/VehicleFaking.csproj", "VehicleFaking/"]
RUN dotnet restore Vehicle/Vehicle.csproj
COPY . .

WORKDIR /src/VehicleFaking
RUN dotnet build VehicleFaking.csproj -c Release -o /app

FROM build as publish
RUN dotnet publish VehicleFaking.csproj -c Release -o /app

FROM base as final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT [ "dotnet" , "VehicleFaking.dll"]